server:
  port: 1010
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: username
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
phnbook:
  messages:
    saveSucc: Contact Saved Succesfully
    saveFail: Failed to save the contact
    updateSucc: Contact Updated Succesfully
logging:
  file:
    name: PHONEBOOK-APP.log